---
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop # TESTING PHASE `DROPPING EVERYTHING IN THE DATA BASE`, NOT FOR PRODUCTION
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  mail: # SIMPLE DUMMY EMAIL CLIENT `https://github.com/maildev/maildev`
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
