server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
      - id: authenticatorModule
        uri: http://localhost:8080/
        predicates:
          - Path=/api/**,/attempts,/attempts/**,/users/**, /login/**
      - id: consumerModule
        uri: http://localhost:8082/
        predicates:
          - Path=/consumer/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
