server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
      - id: authenticatorModule
        uri: http://localhost:8080/
        predicates:
          - Path=/api/registration/**, /login/**
      - id: geoLocatorModule
        uri: http://localhost:808/
        predicates:
          - Path=//**
      - id: userAppModule
        uri: http://localhost:808/
        predicates:
          - Path=/api/session/usr/project_selection/**, /api/session/**, /api/session/usr/**, api/user/bio/**,/api/session/usr/profile/**
      - id: projectMangerModule
        uri: http://localhost:808/
        predicates:
          - Path=/api/user/project_handler/**
      - id: chatAppModule
        uri: http://localhost:808/
        predicates:
          - Path=/getMessages/**, /sendMessage/**, /sendImage/**, /getImage/**
      - id: notificationAppModule
        uri: http://localhost:808/
        predicates:
          - Path=/notification/**   
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
