server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
      - id: userProfilerModule
        uri: http://localhost:8081/
        predicates:
          - Path=/api/session/usr/**, /api/user/**, /api/session/**, /api/user/userauth**

      - id: projectMangerModule
        uri: http://localhost:8082/
        predicates:
          - Path=/api/project/applicant_handler/**, /api/project/project_handler/**
      
      - id: notificationAppModule
        uri: http://localhost:8083/
        predicates:
          - Path=/notification/**   

      - id: geoLocatorModule
        uri: http://localhost:8084/
        predicates:
          - Path=//**
      
      - id: chatAppModule
        uri: http://localhost:8085/
        predicates:
          - Path=/getMessages/**, /sendMessage/**, /sendImage/**, /getImage/**
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
